# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.ohai.plugins_dir = "/var/ohai/custom_plugins"
  config.vm.box = "chef-template"
  config.vm.hostname = "web3"
  config.vm.network "private_network", ip: "192.168.122.14"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "512"
  end

end
